from fastapi.testclient import TestClient

from app.main import app
from tests.http import DEMO_MERCHANT, DEMO_PASSWORD, authenticated_client


def test_login_rejects_wrong_password():
    client = TestClient(app)
    response = client.post(
        "/api/auth/login",
        json={"merchant_id": DEMO_MERCHANT, "password": "wrong-password"},
    )
    assert response.status_code == 401


def test_login_rejects_unknown_merchant():
    client = TestClient(app)
    response = client.post(
        "/api/auth/login",
        json={"merchant_id": "mid_other_merchant", "password": DEMO_PASSWORD},
    )
    assert response.status_code == 401


def test_login_success_and_me():
    client = authenticated_client()
    me = client.get("/api/auth/me")
    assert me.status_code == 200
    assert me.json()["merchant_id"] == DEMO_MERCHANT


def test_logout_without_session_succeeds():
    client = TestClient(app)
    response = client.post("/api/auth/logout")
    assert response.status_code == 200
    assert response.json()["status"] == "signed_out"


def test_logout_revokes_session():
    client = authenticated_client()
    assert client.get("/api/auth/me").status_code == 200
    logged_out = client.post("/api/auth/logout")
    assert logged_out.status_code == 200
    assert client.get("/api/auth/me").status_code == 401
    assert client.get("/api/dashboard").status_code == 401


def test_recovery_amount_comes_from_server_not_client():
    client = authenticated_client()
    dash = client.get("/api/dashboard?period=2026_H2").json()["financial_status"]
    remaining = round(dash["potential_recovery_inr"] - dash["recovery_requested_inr"], 2)
    created = client.post(
        "/api/recovery-requests",
        json={
            "period": "2026_H2",
            "claim_scope": "period",
            "summary": "Combined recovery request generated by automated tests.",
            "recipient": "Razorpay Support",
            "amount_requested": 1.00,
        },
        headers={"Idempotency-Key": "test-recovery-2026h2-1"},
    )
    if remaining <= 0:
        assert created.status_code == 400, created.text
        return
    assert created.status_code == 200, created.text
    body = created.json()
    assert body["amount_requested"] == remaining
    replay = client.post(
        "/api/recovery-requests",
        json={
            "period": "2026_H2",
            "claim_scope": "period",
            "summary": "Combined recovery request generated by automated tests.",
        },
        headers={"Idempotency-Key": "test-recovery-2026h2-1"},
    )
    assert replay.status_code == 200
    assert replay.json()["request_id"] == body["request_id"]


def test_export_statement_is_csv():
    client = authenticated_client()
    response = client.get("/api/exports/statement.csv?period=2026_H2")
    assert response.status_code == 200
    assert "text/csv" in response.headers["content-type"]
    assert b"transaction_id" in response.content


def test_payments_do_not_expose_pii():
    client = authenticated_client()
    response = client.get("/api/payments?period=2026_H2&page=1&page_size=20")
    assert response.status_code == 200
    for row in response.json()["data"]:
        lowered = {str(key).lower() for key in row.keys()}
        assert "email" not in lowered
        assert "contact" not in lowered
        assert "phone" not in lowered
        assert "customer_email" not in lowered


def test_statement_unknown_period_is_400():
    client = authenticated_client()
    response = client.get("/api/statement?period=1999_H1")
    assert response.status_code == 400
    assert response.json()["detail"]["code"] == "invalid_period"


def test_paise_rounding_edges():
    from app.core.money import inr_to_paise, paise_to_inr

    assert inr_to_paise(0) == 0
    assert inr_to_paise("0.01") == 1
    assert inr_to_paise("0.015") == 2  # bankers/half-even on 1.5 paise -> 2
    assert paise_to_inr(1) == 0.01
    assert paise_to_inr(100000000) == 1000000.0
    assert inr_to_paise("-1") == -100
    assert inr_to_paise(None) == 0
    assert inr_to_paise("not-a-number") == 0
